package com.gutschke.wgrtc.signalling

import com.goterl.lazysodium.LazySodium
import com.goterl.lazysodium.LazySodiumAndroid
import com.goterl.lazysodium.SodiumAndroid
import com.goterl.lazysodium.interfaces.Box
import com.goterl.lazysodium.interfaces.GenericHash
import com.goterl.lazysodium.interfaces.SecretBox
import java.security.MessageDigest
import java.security.SecureRandom

// Curve25519 constants (X25519 + WireGuard). We don't import them
// from the lazysodium API because the relevant interface name differs
// between versions and these values are wire-format constants anyway.
private const val X25519_KEY_BYTES = 32

/**
 * Crypto primitives, sized & framed identically to the Python daemon
 * (see github/wireguardrtc). Where the daemon writes
 * `BLAKE2b(shared, key=LABEL[:32], length=32)` we do the same here so
 * the wire format is byte-identical.
 *
 * **Domain separation labels** — these are wire-format constants;
 * changing them silently breaks compatibility with the daemon.
 */
internal object CryptoLabels {
    /** Used by signalling-OFFER messages. Matches PROTOCOL_LABEL in the daemon. */
    @JvmStatic val SIGBOX = "wg-peerjs/v1/sigbox".toByteArray(Charsets.UTF_8)

    /** Used by ENROLL/ENROLL_OK/ENROLL_ERR messages. Matches LABEL_ENROLL. */
    @JvmStatic val ENROLL = "wg-peerjs/v1/enroll".toByteArray(Charsets.UTF_8)
}

/**
 * Single LazySodium handle. Cheap to construct but holds JNA
 * native-library references — keep one per process.
 *
 * The default is `LazySodiumAndroid`, which loads the bundled
 * `libsodiumjni.so` shipped inside the AAR. Plain-JVM tests cannot
 * load that .so (the bundled binaries target Android ABIs only) — they
 * call [setForTest] in a `@BeforeAll` to swap in `LazySodiumJava`,
 * which delegates to a JVM-side libsodium loaded from the JAR. The
 * variants share the same superclass and the methods we use, so the
 * swap is transparent to production code.
 */
object Sodium {
    @Volatile
    private var override: LazySodium? = null
    private val default: LazySodium by lazy { LazySodiumAndroid(SodiumAndroid()) }

    val instance: LazySodium
        get() = override ?: default

    /** Test seam. Pass `null` to revert to the production default. */
    @Synchronized
    fun setForTest(impl: LazySodium?) { override = impl }
}

/** Result of a Curve25519 / WireGuard keypair generation. */
data class KeyPair(val publicKey: ByteArray, val privateKey: ByteArray) {
    init {
        require(publicKey.size == 32) { "pub must be 32 bytes" }
        require(privateKey.size == 32) { "priv must be 32 bytes" }
    }
}

/**
 * Derive a Curve25519 public key from a private key
 * (X25519's `crypto_scalarmult_base`). Useful for resurrecting a
 * peer's public from its stored private when the configfile only
 * carries the private (wg-quick semantics).
 */
fun pubKeyFromPrivate(privateKey: ByteArray): ByteArray {
    require(privateKey.size == X25519_KEY_BYTES) { "private key must be 32 bytes" }
    val pub = ByteArray(X25519_KEY_BYTES)
    val ok = Sodium.instance.cryptoScalarMultBase(pub, privateKey)
    check(ok) { "cryptoScalarMultBase failed" }
    return pub
}

/** Generate a fresh Curve25519 keypair (suitable for both X25519 and WireGuard). */
fun generateKeyPair(): KeyPair {
    val pub = ByteArray(Box.PUBLICKEYBYTES)
    val priv = ByteArray(Box.SECRETKEYBYTES)
    Sodium.instance.cryptoBoxKeypair(pub, priv)
    return KeyPair(pub, priv)
}

/**
 * X25519 ECDH. Returns the 32-byte shared secret. Note that
 * libsodium's scalarmult does NOT include the per-key clamping that
 * crypto_box does internally — we rely on input keys having been
 * generated by [generateKeyPair] (or imported from WireGuard, which
 * also generates clamped keys via the standard Curve25519 procedure).
 */
fun x25519(privateKey: ByteArray, peerPublicKey: ByteArray): ByteArray {
    require(privateKey.size == X25519_KEY_BYTES) { "private key must be 32 bytes" }
    require(peerPublicKey.size == X25519_KEY_BYTES) { "public key must be 32 bytes" }
    val shared = ByteArray(X25519_KEY_BYTES)
    val ok = Sodium.instance.cryptoScalarMult(shared, privateKey, peerPublicKey)
    check(ok) { "scalarmult failed" }
    return shared
}

/**
 * Keyed BLAKE2b producing a 32-byte digest. Matches the daemon's
 * `_nacl_blake2b(in, key=label, digest_size=32)`.
 */
fun blake2b32(input: ByteArray, key: ByteArray): ByteArray {
    val out = ByteArray(GenericHash.BYTES)
    val ok = Sodium.instance.cryptoGenericHash(out, out.size, input, input.size.toLong(), key, key.size)
    check(ok) { "blake2b failed" }
    return out
}

/**
 * Derive the signalling-OFFER secretbox key.
 *
 * shared = X25519(my_priv, peer_pub)
 * key = BLAKE2b32(shared, key=SIGBOX[:32])
 *
 * Identical to the daemon's `derive_secretbox_key`.
 */
fun deriveSigboxKey(myPriv: ByteArray, peerPub: ByteArray): ByteArray {
    val shared = x25519(myPriv, peerPub)
    return blake2b32(shared, CryptoLabels.SIGBOX.copyOf(minOf(CryptoLabels.SIGBOX.size, 32)))
}

/**
 * Derive the per-token enrollment key.
 *
 * shared = X25519(my_priv, peer_pub)
 * enrollKey = BLAKE2b32(shared, key=ENROLL[:32])
 * finalKey = BLAKE2b32(enrollKey, key=token)
 *
 * Identical to the daemon's `derive_enroll_key`.
 */
fun deriveEnrollKey(myPriv: ByteArray, peerPub: ByteArray, token: ByteArray): ByteArray {
    val shared = x25519(myPriv, peerPub)
    val enrollKey = blake2b32(shared, CryptoLabels.ENROLL.copyOf(minOf(CryptoLabels.ENROLL.size, 32)))
    return blake2b32(enrollKey, token)
}

/**
 * XSalsa20-Poly1305 secretbox encrypt with a fresh random nonce.
 * Returns NaCl-style "easy" ciphertext: [nonce(24) || boxed].
 */
fun secretboxEncrypt(plaintext: ByteArray, key: ByteArray): ByteArray {
    require(key.size == SecretBox.KEYBYTES) { "key must be 32 bytes" }
    val nonce = ByteArray(SecretBox.NONCEBYTES)
    SecureRandom().nextBytes(nonce)
    val cipher = ByteArray(plaintext.size + SecretBox.MACBYTES)
    val ok = Sodium.instance.cryptoSecretBoxEasy(cipher, plaintext, plaintext.size.toLong(), nonce, key)
    check(ok) { "secretbox encrypt failed" }
    return nonce + cipher
}

/** Decrypt a [nonce(24) || boxed] ciphertext. Returns null on auth-tag failure. */
fun secretboxDecrypt(ciphertext: ByteArray, key: ByteArray): ByteArray? {
    require(key.size == SecretBox.KEYBYTES)
    if (ciphertext.size < SecretBox.NONCEBYTES + SecretBox.MACBYTES) return null
    val nonce = ciphertext.copyOfRange(0, SecretBox.NONCEBYTES)
    val boxed = ciphertext.copyOfRange(SecretBox.NONCEBYTES, ciphertext.size)
    val plain = ByteArray(boxed.size - SecretBox.MACBYTES)
    val ok = Sodium.instance.cryptoSecretBoxOpenEasy(plain, boxed, boxed.size.toLong(), nonce, key)
    return if (ok) plain else null
}

/**
 * Compute a routing-id matching the daemon's
 * `routing_id(pubkey_b64, salt) = SHA256(pubkey_b64.utf8 ++ salt).hex()`.
 *
 * **`salt` is bytes** — exactly the bytes the daemon stores (which are
 * the bytes of the original base64-encoded-salt string in the config
 * file, NOT decoded base64). When parsing a `wgrtc-enroll://` URI,
 * the `salt` parameter is URL-safe-base64-decoded; the resulting bytes
 * are these.
 */
fun routingId(publicKeyBase64: String, salt: ByteArray): String {
    val sha = MessageDigest.getInstance("SHA-256")
    sha.update(publicKeyBase64.toByteArray(Charsets.UTF_8))
    sha.update(salt)
    return sha.digest().joinToString("") { "%02x".format(it) }
}
